#! /usr/bin/env python

#import roslib; roslib.load_manifest('nameit')

from nameitu import nameitu

#rosimports
import rospy
#import nameit.srv.NameItGoogle
#NameItGoogle.srv import *
from sensor_msgs.msg import CompressedImage
from nameit.srv import *

def nameitgoogle(req):
  #print req
  type(req)
  return nameitu(req.compimg.data)

def init():
    rospy.init_node('imagegoogler')
    s = rospy.Service('nameitgoogle', NameItGoogle, nameitgoogle)
    print "Ready to tag Things"
    rospy.spin()

if __name__ == "__main__":
    init()