#!/usr/bin/python

import sys
import os

#rosimports
import rospy
from nameit.srv import *

#std_msgs/Header header
#string format
#uint8[] data

def whatisthis(img):
  rospy.wait_for_service('nameitgoogle')
  try:
    nameit = rospy.ServiceProxy('nameitgoogle', NameItGoogle)
    imc=NameItGoogle()
    #imc.header.seq = 0
    #imc.header.stamp = 0
    #imc.header.frame_id "0"
    #imc.format="png"
    imc.data=img
    resp1 = nameit( imc )
    return resp1.sum
  except rospy.ServiceException, e:
    print "Service call failed: %s"%e

def main(argv):
    import argparse
    parser = argparse.ArgumentParser(description='Take Pictures and ask Google to name them')
    parser.add_argument('-s', '--snap', action='store_true', help='take a snapshot')
    parser.add_argument('-c', '--cam', nargs='?', type=int, help='use cam Number N defaults to 0', default=0)
    parser.add_argument('NAME', nargs='?', help='Filename defaults to snap.jpg', default="snap.jpg")
    cmdline_args = parser.parse_args(sys.argv[1:]) #cut the program-name off the list 
    
    #print  cmdline_args
    
    picture_file=cmdline_args.NAME
    
    if cmdline_args.snap:
      snapshot(picture_file,cmdline_args.cam)
      #snapshot(picture_file,0)
    
    if not os.path.exists(picture_file):
      print "missing " + picture_file + " you may want to capture it using -s (-h for Help)"
      sys.exit(-1)
        
    imgbuff = open(picture_file)
    img=imgbuff.read()
    ret = whatisthis(img)
    imgbuff.close()
    for j in ret:
      for i in j:
        print i
      print "################################################################"

    

if __name__ == "__main__":
    sys.exit(main(sys.argv)) 
